### ISSUE TITLE
Unhandled event loop exception when adding multiple messages at the bottom of the interaction

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#322]
I added a couple of messages at the bottom of the interaction so that it has to grow. Intermittently the error below showed up. I am not sure how to reproduce that reliably and efficiently though.

```
An internal error occurred during: "Computing logical model".
dependency cycle: [MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), Message(LWSeqd::Interaction1::<unnamed>, Edge_Message), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), Message(LWSeqd::Interaction1::<unnamed>, Edge_Message)]
```

```
!ENTRY org.eclipse.ui 4 0 2018-07-12 18:12:15.529
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: dependency cycle: [MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), Message(LWSeqd::Interaction1::<unnamed>, Edge_Message), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), MessageOccurrenceSpecification(LWSeqd::Interaction1::<unnamed>), Message(LWSeqd::Interaction1::<unnamed>, Edge_Message)]
	at org.eclipse.papyrus.uml.interaction.internal.graph.EdgeImpl.checkForCycle(EdgeImpl.java:156)
	at org.eclipse.papyrus.uml.interaction.internal.graph.EdgeImpl.<init>(EdgeImpl.java:41)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:97)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:93)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:115)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer$EdgeFactory.caseMessage(GraphComputer.java:192)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer$EdgeFactory.caseMessage(GraphComputer.java:1)
	at org.eclipse.uml2.uml.util.UMLSwitch.doSwitch(UMLSwitch.java:4667)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.compute(GraphComputer.java:88)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphImpl.<init>(GraphImpl.java:77)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphImpl.getInstance(GraphImpl.java:96)
	at org.eclipse.papyrus.uml.interaction.graph.Graph.compute(Graph.java:179)
	at org.eclipse.papyrus.uml.interaction.internal.model.impl.InteractionModelBuilder.<init>(InteractionModelBuilder.java:44)
	at org.eclipse.papyrus.uml.interaction.internal.model.impl.InteractionModelBuilder.getInstance(InteractionModelBuilder.java:57)
	at org.eclipse.papyrus.uml.interaction.model.MInteraction.getInstance(MInteraction.java:56)
	at org.eclipse.papyrus.uml.diagram.sequence.runtime.internal.edit.policies.LogicalModelCreationEditPolicy.getCreateElementAndViewCommand(LogicalModelCreationEditPolicy.java:50)
	at org.eclipse.gmf.runtime.diagram.ui.editpolicies.CreationEditPolicy.getCommand(CreationEditPolicy.java:87)
	at org.eclipse.gef.editparts.AbstractEditPart.getCommand(AbstractEditPart.java:502)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart.access$1(GraphicalEditPart.java:1)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart$1.run(GraphicalEditPart.java:482)
	at org.eclipse.papyrus.infra.emf.readonly.PapyrusROTransactionalEditingDomain.runExclusive(PapyrusROTransactionalEditingDomain.java:271)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart.getCommand(GraphicalEditPart.java:477)
	at org.eclipse.papyrus.uml.diagram.sequence.runtime.internal.edit.policies.SequenceDiagramPopupBarEditPolicy$DefaultTool.getCommand(SequenceDiagramPopupBarEditPolicy.java:191)
	at org.eclipse.gmf.runtime.diagram.ui.tools.AbstractPopupBarTool.isCommandEnabled(AbstractPopupBarTool.java:96)
	at org.eclipse.papyrus.infra.gmfdiag.common.editpolicies.PapyrusPopupBarEditPolicy.addPopupBarDescriptor(PapyrusPopupBarEditPolicy.java:325)
	at org.eclipse.papyrus.infra.gmfdiag.common.editpolicies.PapyrusPopupBarEditPolicy.addPopupBarDescriptor(PapyrusPopupBarEditPolicy.java:347)
	at org.eclipse.papyrus.infra.gmfdiag.common.editpolicies.PapyrusPopupBarEditPolicy.addPopupBarDescriptor(PapyrusPopupBarEditPolicy.java:360)
	at org.eclipse.papyrus.infra.gmfdiag.common.editpolicies.PapyrusPopupBarEditPolicy.populatePopupBars(PapyrusPopupBarEditPolicy.java:198)
	at org.eclipse.papyrus.infra.gmfdiag.common.editpolicies.PapyrusPopupBarEditPolicy.showDiagramAssistant(PapyrusPopupBarEditPolicy.java:509)
	at org.eclipse.papyrus.uml.diagram.sequence.runtime.internal.edit.policies.SequenceDiagramPopupBarEditPolicy.showDiagramAssistant(SequenceDiagramPopupBarEditPolicy.java:56)
	at org.eclipse.papyrus.infra.gmfdiag.common.editpolicies.PapyrusPopupBarEditPolicy.mouseHover(PapyrusPopupBarEditPolicy.java:738)
	at org.eclipse.draw2d.Figure.handleMouseHover(Figure.java:920)
	at org.eclipse.draw2d.SWTEventDispatcher.dispatchMouseHover(SWTEventDispatcher.java:190)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseHover(DomainEventDispatcher.java:327)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseHover(LightweightSystem.java:538)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:209)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by planger** [comment]
I couldn't reproduce this anymore with current master.
