### ISSUE TITLE
Prohibit invalid create message creation

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#363]
I am able to create a create message in the following scenario from `Lifeline1` to `Lifeilne2`:
![image](https://user-images.githubusercontent.com/588090/45744330-96bf3200-bbfe-11e8-9913-b575dca37fb1.png)

Executing the addition then leads to:
![image](https://user-images.githubusercontent.com/588090/45744390-bd7d6880-bbfe-11e8-9c5c-b3e625a558d3.png)

```
!ENTRY org.eclipse.core.jobs 4 2 2018-09-19 11:25:14.418
!MESSAGE An internal error occurred during: "Computing logical model".
!STACK 0
java.lang.IllegalArgumentException: dependency cycle: [MessageOccurrenceSpecification(SEQD::Interaction2::<unnamed>), MessageOccurrenceSpecification(SEQD::Interaction2::<unnamed>), Message(SEQD::Interaction2::<unnamed>, Edge_Message), Lifeline{G}(SEQD::Interaction2::Lifeline1, Shape_Lifeline_Header), MessageOccurrenceSpecification(SEQD::Interaction2::<unnamed>), Message(SEQD::Interaction2::<unnamed>, Edge_Message)]
	at org.eclipse.papyrus.uml.interaction.internal.graph.EdgeImpl.checkForCycle(EdgeImpl.java:156)
	at org.eclipse.papyrus.uml.interaction.internal.graph.EdgeImpl.<init>(EdgeImpl.java:41)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:98)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:94)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:116)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer$EdgeFactory.caseMessage(GraphComputer.java:193)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer$EdgeFactory.caseMessage(GraphComputer.java:1)
	at org.eclipse.uml2.uml.util.UMLSwitch.doSwitch(UMLSwitch.java:4667)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.compute(GraphComputer.java:89)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphImpl.<init>(GraphImpl.java:77)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphImpl.getInstance(GraphImpl.java:96)
	at org.eclipse.papyrus.uml.interaction.graph.Graph.compute(Graph.java:179)
	at org.eclipse.papyrus.uml.interaction.internal.model.impl.InteractionModelBuilder.<init>(InteractionModelBuilder.java:44)
	at org.eclipse.papyrus.uml.interaction.internal.model.impl.InteractionModelBuilder.getInstance(InteractionModelBuilder.java:57)
	at org.eclipse.papyrus.uml.interaction.model.MInteraction.getInstance(MInteraction.java:56)
	at org.eclipse.papyrus.uml.interaction.model.MInteraction.getInstance(MInteraction.java:70)
	at org.eclipse.papyrus.uml.interaction.model.internal.view.LogicalModelPage$3.lambda$0(LogicalModelPage.java:200)
	at org.eclipse.papyrus.infra.emf.readonly.PapyrusROTransactionalEditingDomain.runExclusive(PapyrusROTransactionalEditingDomain.java:271)
	at org.eclipse.papyrus.uml.interaction.model.internal.view.LogicalModelPage$3.run(LogicalModelPage.java:200)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

!ENTRY org.eclipse.ui 4 0 2018-09-19 11:25:14.419
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: dependency cycle: [MessageOccurrenceSpecification(SEQD::Interaction2::<unnamed>), MessageOccurrenceSpecification(SEQD::Interaction2::<unnamed>), Message(SEQD::Interaction2::<unnamed>, Edge_Message), Lifeline{G}(SEQD::Interaction2::Lifeline1, Shape_Lifeline_Header), MessageOccurrenceSpecification(SEQD::Interaction2::<unnamed>), Message(SEQD::Interaction2::<unnamed>, Edge_Message)]
	at org.eclipse.papyrus.uml.interaction.internal.graph.EdgeImpl.checkForCycle(EdgeImpl.java:156)
	at org.eclipse.papyrus.uml.interaction.internal.graph.EdgeImpl.<init>(EdgeImpl.java:41)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:98)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:94)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.edge(GraphComputer.java:116)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer$EdgeFactory.caseMessage(GraphComputer.java:193)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer$EdgeFactory.caseMessage(GraphComputer.java:1)
	at org.eclipse.uml2.uml.util.UMLSwitch.doSwitch(UMLSwitch.java:4667)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphComputer.compute(GraphComputer.java:89)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphImpl.<init>(GraphImpl.java:77)
	at org.eclipse.papyrus.uml.interaction.internal.graph.GraphImpl.getInstance(GraphImpl.java:96)
	at org.eclipse.papyrus.uml.interaction.graph.Graph.compute(Graph.java:179)
	at org.eclipse.papyrus.uml.interaction.internal.model.impl.InteractionModelBuilder.<init>(InteractionModelBuilder.java:44)
	at org.eclipse.papyrus.uml.interaction.internal.model.impl.InteractionModelBuilder.getInstance(InteractionModelBuilder.java:57)
	at org.eclipse.papyrus.uml.interaction.model.MInteraction.getInstance(MInteraction.java:56)
	at org.eclipse.papyrus.uml.interaction.model.MInteraction.getInstance(MInteraction.java:70)
	at org.eclipse.papyrus.uml.diagram.sequence.runtime.internal.edit.parts.LifelineBodyEditPart.getMInteraction(LifelineBodyEditPart.java:129)
	at org.eclipse.papyrus.uml.diagram.sequence.runtime.internal.edit.parts.LifelineBodyEditPart.computeLifelineHeight(LifelineBodyEditPart.java:104)
	at org.eclipse.papyrus.uml.diagram.sequence.runtime.internal.edit.parts.LifelineBodyEditPart.refreshBounds(LifelineBodyEditPart.java:91)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.ShapeEditPart.refreshVisuals(ShapeEditPart.java:205)
	at org.eclipse.gef.editparts.AbstractEditPart.refresh(AbstractEditPart.java:725)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.refresh(AbstractGraphicalEditPart.java:644)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart.access$3(GraphicalEditPart.java:1)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart$3.run(GraphicalEditPart.java:861)
	at org.eclipse.papyrus.infra.emf.readonly.PapyrusROTransactionalEditingDomain.runExclusive(PapyrusROTransactionalEditingDomain.java:271)
	at org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart.refresh(GraphicalEditPart.java:851)
	at org.eclipse.papyrus.infra.gmfdiag.common.helper.DiagramHelper.refresh(DiagramHelper.java:55)
	at org.eclipse.papyrus.infra.gmfdiag.common.helper.DiagramHelper.refresh(DiagramHelper.java:64)
	at org.eclipse.papyrus.infra.gmfdiag.common.helper.DiagramHelper.refresh(DiagramHelper.java:64)
	at org.eclipse.papyrus.infra.gmfdiag.common.helper.DiagramHelper.refresh(DiagramHelper.java:64)
	at org.eclipse.papyrus.infra.gmfdiag.common.helper.DiagramHelper.refresh(DiagramHelper.java:84)
	at org.eclipse.papyrus.infra.gmfdiag.common.helper.DiagramHelper$1.run(DiagramHelper.java:149)
	at org.eclipse.papyrus.infra.ui.util.UIUtil$UIExecutorService$RunnableWrapper.run(UIUtil.java:536)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4577)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4186)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by planger** [comment]
Ok, great. So we can close this issue then, right? Please re-open, if I misunderstood your comment. Thanks!
